config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  get 'cursos' => 'cursos#find_by_curso'
  get 'aluno' => 'alunos#index'
  get 'registroacademico' => 'registro_academicos#index'
  get 'biblioteca' => 'bibliotecas#index'
  get 'buscapedido' => 'home#search'
  get 'pedidos_registro' => 'registro_academicos#pedidos'
  get 'pedidos_biblioteca' => 'bibliotecas#pedidos'
  root 'home#index'
  get 'pedido_atestados/get_pedido/:id' => "pedido_atestados#get_pedido", as: "pedido_atestados_get_pedido"
  get 'pedido_atestados/get_situacao' => "pedido_atestados#get_situacao", as: "pedido_atestados_get_situacao"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pedido_atestados
end

app/models/pedido_atestado.rb
# == Schema Information
#
# Table name: pedidos
#
#  id               :bigint(8)        not null, primary key
#  nome             :string
#  matricula        :string
#  pasta            :string
#  periodo          :string
#  turno            :string
#  anoLetivo        :string
#  telefone         :string
#  celular          :string
#  email            :string
#  finalidadePedido :text
#  type             :string
#  curso_id         :bigint(8)
#  situacao_id      :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class PedidoAtestado < Pedido
end

app/controllers/pedido_atestados_controller.rb
# == Schema Information
#
# Table name: pedidos
#
#  id               :bigint(8)        not null, primary key
#  nome             :string
#  matricula        :string
#  pasta            :string
#  periodo          :string
#  turno            :string
#  anoLetivo        :string
#  telefone         :string
#  celular          :string
#  email            :string
#  finalidadePedido :text
#  type             :string
#  curso_id         :bigint(8)
#  situacao_id      :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class PedidoAtestadosController < ApplicationController
  before_action :set_pedido_atestado, only: [:show, :edit, :update, :destroy]

  COD_INDEFERIDO = 4
  COD_NEGADO = 3
  # GET /pedido_atestados
  # GET /pedido_atestados.json
  def index
    @pedido_atestados = PedidoAtestado.all
  end

  # GET /pedido_atestados/1
  # GET /pedido_atestados/1.json
  def show
  end

  # GET /pedido_atestados/new
  def new
    @pedido_atestado = PedidoAtestado.new
    @pedido_atestado.situacao_id = 1
  end

  # GET /pedido_atestados/1/edit
  def edit
  end

  # POST /pedido_atestados
  # POST /pedido_atestados.json
  def create
    @pedido_atestado = PedidoAtestado.new(pedido_atestado_params)

    respond_to do |format|
      if @pedido_atestado.save
        format.json { }
        format.html { redirect_to aluno_path(), notice: 'Pedido encaminhado com sucesso.' }
      else
        format.html { render :new }
        format.json { render json: @pedido_atestado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_atestados/1
  # PATCH/PUT /pedido_atestados/1.json
  def update
    if current_usuario.tipo == "biblioteca" then
      @pagina_home = pedidos_biblioteca_path
    else
      @pagina_home = pedidos_registro_path
    end

    respond_to do |format|
      if @pedido_atestado.update(pedido_atestado_params) then
        if @pedido_atestado.situacao_id != COD_NEGADO and @pedido_atestado.situacao_id != COD_INDEFERIDO then
          @pedido_atestado.update_column(:observacao, nil)
        end        
        format.html { redirect_to @pagina_home, notice: 'Pedido atualizado com sucesso!' }
        format.json { render @pagina_home, status: :ok, location: @pedido_atestado }
      else
        format.html { render @pagina_home }
        format.json { render json: @pedido_atestado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_atestados/1
  # DELETE /pedido_atestados/1.json
  def destroy
    @pedido_atestado.destroy
    respond_to do |format|
      format.html { redirect_to pedido_atestados_url, notice: 'Pedido excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  def get_pedido
    @pedido = PedidoAtestado.find(params[:id])
    if [1, 3].include? @pedido.situacao_id then
      @situacoes = Situacao.find(1,2,3)
    else
      @situacoes = Situacao.find(2,4,5,6)
    end
  end

  def get_situacao
    @pedido_atestado = PedidoAtestado.where(pasta: params[:pasta]).last
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido_atestado
      @pedido_atestado = PedidoAtestado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_atestado_params    
      params.require(:pedido_atestado).permit(:type, :nome, :matricula, :pasta, :periodo, :turno, :telefone, :celular, :email, :finalidadePedido, :curso_id, :situacao_id, :observacao)
    end
end

app/helpers/pedido_atestados_helper.rb
# == Schema Information
#
# Table name: pedidos
#
#  id               :bigint(8)        not null, primary key
#  nome             :string
#  matricula        :string
#  pasta            :string
#  periodo          :string
#  turno            :string
#  anoLetivo        :string
#  telefone         :string
#  celular          :string
#  email            :string
#  finalidadePedido :text
#  type             :string
#  curso_id         :bigint(8)
#  situacao_id      :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

module PedidoAtestadosHelper
end

app/views/pedido_atestados/_andamento_pedido.html.erb
<div class="alert" role="alert">
  <section>
    <small><strong>Pasta:</strong> <%= @pedido_atestado.pasta %></small>
    <br>
    <small><strong>Data do pedido:</strong> <%= @pedido_atestado.created_at.strftime("%d/%m/%Y") %></small>
    <hr>      
  </section>
  <p id="msg-andamento" class="text-center"></p>  
</div>

<div class="progress" style="height: 30px; font-weight: bold">
  <div id="status-bar" class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><%=@pedido_atestado.situacao.descricao%></div>
</div>

<script type="text/javascript">
  switch (<%= @pedido_atestado.situacao_id %>) {
    case 1:
      newprogress = 15;
      mensagem = "Aguardando liberação do Nada Consta pelo setor bibliotecário."
      break;
    case 2:
      newprogress = 40;
      mensagem = "Encaminhado ao Registro Acadêmico para digitalização."
      break;

    case 3:
      newprogress = 100;
      $('#status-bar').css('background-color', 'red');
      mensagem = "Nada Consta recusado devido a pendências no setor bibliotecário.<br> Obervação: <%= @pedido_atestado.observacao %> <br> Acesse <a href='http://gru.centro.iff.edu.br/'>http://gru.centro.iff.edu.br/</a>.";
      break;
    
    case 4:
      newprogress = 100;
      $('#status-bar').css('background-color', 'red');
      mensagem = "Pedido Indeferido devido a pendências no setor registro acadêmico.<br> Obervação: <%= @pedido_atestado.observacao %>.";
      break;

    case 5:
      newprogress = 80;
      mensagem = "O documento encontra-se disponível no Registro Acadêmico."
      break;

    case 6:
      newprogress = 100;
      mensagem = "Documento retirado em <%= @pedido_atestado.updated_at.strftime("%d/%m/%Y") %>."
      $('#status-bar').css('background-color', 'green');
      break;

    default:
      newprogress = 0;
      mensagem = "Nada Encontrado!"      
      break;      
  }
  document.getElementById('msg-andamento').innerHTML = mensagem;
  $('#status-bar').attr('aria-valuenow', newprogress).css('width', newprogress + "%");
</script>

app/views/pedido_atestados/_detalhes_pedido.html.erb
<div class="container-fluid py-3 z-depth-1 div-modal-default">
  <p class="text-center">Solicitado <%= I18n.l(@pedido.created_at, format: :long) %></p>
  <hr>
  <div class="form-row mb-1">
    <strong class="text-left pr-2">Solicitante: </strong>
    <%= @pedido.nome %>
  </div>

  <div class="form-row mb-1">
    <strong class="text-left pr-2">Pasta: </strong>
    <%= @pedido.pasta %>
  </div>

  <div class="form-row mb-1">
    <strong class="text-left pr-2">Matrícula: </strong>
    <%= @pedido.matricula %>
  </div>

  <div class="form-row mb-1">
    <strong class="text-left pr-2">Curso:</strong>
    <%= @pedido.curso.descricao %> / <%= @pedido.periodo + "º #{@pedido.curso.nivelEscolaridade === "Superior" ? "período" : "módulo"}"%> - <%= @pedido.turno %>
  </div>

  <div class="form-row mb-1">
    <strong class="text-left pr-2">Contatos:</strong>
    <%= @pedido.email %> <%= !@pedido.telefone.blank? ? "| "+ @pedido.telefone : ""  %> <%= !@pedido.celular.blank? ? "| "+ @pedido.celular : ""  %>
  </div>

  <div class="form-row mb-1">
    <strong class="text-left pr-2">Finalidade do pedido:</strong>
    <%= @pedido.finalidadePedido %>
  </div>
</div>

<%= render partial: 'pedido_atestados/edit', pedido_atestado: @pedido %>

app/views/pedido_atestados/_edit.html.erb
<%= simple_form_for(@pedido, local: true) do |form| %>
  <div class="div-modal-default alert-info z-depth-1 mt-3 py-3 text-center">
    <% @situacoes.each do |situacao| %>
      <div class="custom-control custom-radio custom-control-inline">
        <% if @pedido.situacao_id == situacao.id %>
          <input type="radio" checked value="<%=situacao.id%>" name="pedido_atestado[situacao_id]" class="custom-control-input radioSituacao" id='<%="pedido_atestado_situacao_id_#{situacao.id}"%>'>
        <% else %>
          <input type="radio" value="<%=situacao.id%>" name="pedido_atestado[situacao_id]" class="custom-control-input radioSituacao" id='<%="pedido_atestado_situacao_id_#{situacao.id}"%>'>
        <% end %>
        <label class="custom-control-label" for="<%="pedido_atestado_situacao_id_#{situacao.id}" %>"><%= situacao.descricao %></label>
      </div>
    <% end %>

    <div class="mx-3 pt-3" style="display: none" id="obs" >
      <%= form.text_area :observacao, placeholder:'Justifique a negação...', :class => "form-control", :maxlength => '220' %>
    </div>
  </div>

  <div class="actions text-center pt-2">
    <%= form.submit 'Atualizar Situação', :class => 'btn blue-default' %>
  </div>
<% end %>

<script type="text/javascript">
  var obs = document.getElementById('obs');
  var situacaoNegado = document.getElementById('pedido_atestado_situacao_id_3');
  var situacaoIndeferido = document.getElementById('pedido_atestado_situacao_id_4');

  if ((situacaoNegado != null && situacaoNegado.checked == true) || (situacaoIndeferido != null && situacaoIndeferido.checked == true)) {
    obs.style.display="block";
  } else {
    obs.style.display="none";
  }

  $('.radioSituacao').change(function(event) {
    var situacao = $(this);
    var obs = document.getElementById('obs');
    
    if (situacao[0].value == 3 || situacao[0].value == 4) {
      obs.style.display="block";
    } else {
      obs.style.display="none";
    }
  });
</script>

app/views/pedido_atestados/_form.html.erb
<% if pedido_atestado.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <ul>
    <% pedido_atestado.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= simple_form_for(@pedido_atestado, local: true) do |form| %>
  <section class="form-default">
    <div class="form-row mb-4">
      <div class="col">
        <%= form.text_field :nome, :class => "form-control", :placeholder => 'Nome' %>
      </div>
      <div class="col">
        <%= form.text_field :matricula, onkeypress: 'return SomenteNumero(event)', maxlength: '12', :class => "form-control", :placeholder => 'Matrícula'  %>
      </div>
      <div class="col">
        <%= form.text_field :pasta, onkeypress: 'return SomenteNumero(event)', maxlength: '6', :class => "form-control", :placeholder => 'Pasta'  %>
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col">
        <%= form.input :curso_id, :as => :select, :collection => Curso.all.collect { |curso| [curso.descricao, curso.id] }, :label => false, :prompt => 'Selecione um curso', input_html: {:class => "browser-default custom-select", :id => "curso_id"} %>
      </div>
      <div class="col">
        <%= form.input :periodo, :as => :select, :collection => Curso.all.collect { |curso| ["", curso.quantidadePeriodo] }, :label => false, :prompt => 'Selecione o período/módulo', input_html: {:class => "browser-default custom-select", :id => "periodo", :disabled => "true"} %>
      </div>

      <div class="col" id="div-turno">
        <%= form.label :turno, "Turno:", :class => 'px-2 pt-2' %>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" value="Diurno" name="pedido_atestado[turno]" class="custom-control-input" id="pedido_atestado_turno_diurno">
          <label class="custom-control-label" for="pedido_atestado_turno_diurno">Diurno</label>
        </div>

        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" value="Noturno" name="pedido_atestado[turno]" class="custom-control-input" id="pedido_atestado_turno_noturno">
          <label class="custom-control-label" for="pedido_atestado_turno_noturno">Noturno</label>
        </div>

        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" value="Integral" name="pedido_atestado[turno]" class="custom-control-input" id="pedido_atestado_turno_integral">
          <label class="custom-control-label" for="pedido_atestado_turno_integral">Integral</label>
        </div>
      </div>
    </div>

    <div class="form-row mb-4">
      <div class="col">
        <%= form.text_field :email, type: 'email', placeholder:'Email', :class => "form-control" %>
      </div>
      <div class="col">
        <%= form.text_field :telefone, onkeyup: 'telefone(this);', placeholder:'Telefone', :class => "form-control" %>
      </div>
      <div class="col">
        <%= form.text_field :celular, onkeyup: 'celular(this);', placeholder:'Celular', :class => "form-control" %>
      </div>
    </div>
    <div class="mb-4 col-md-6 offset-md-3">
      <%= form.text_area :finalidadePedido, placeholder:'Informe o motivo da solicitação...', :class => "form-control", :maxlength => '220' %>
    </div>
    <div class="form-row mb-4" style="display: none">
      <%= form.label :situacao_id %>
      <%= form.collection_select :situacao_id, Situacao.all, :id, :descricao %>
    </div>

    <div class="actions text-center">
      <%= form.submit 'Solicitar Documento', :class => 'btn blue-default' %>
    </div>
  </section>
<% end %>

app/views/pedido_atestados/_form_busca.html.erb
<%= simple_form_for(path, method: "get") do |form| %>
  <div id="filtros" class="form-row bg-gray z-depth-1-half mb-3">
    <div class="col-md-3">
      <%= form.input :curso, :as => :select, :label => false, :collection => Curso.all.collect { |curso| [curso.descricao, curso.id] }.uniq, :prompt => 'Selecione um curso', input_html: {:class => "browser-default custom-select", :name => "curso"} %>
    </div>
    <div class="col-md-3">
      <%= form.input :nivel, :as => :select, :label => false, :collection => Curso.all.collect { |curso| [curso.nivelEscolaridade, curso.nivelEscolaridade] }.uniq, :prompt => 'Selecione um nível', input_html: {:class => "browser-default custom-select pull-left", :name => "nivel"} %>
    </div>
    <div class="col-md-3">
      <%= form.input :situacao_id, :as => :select, :label => false, :collection => @situacao_busca.collect { |situacao| [situacao.descricao,
        situacao.id] }.uniq, :prompt => 'Selecione a situação', input_html: {:class => "browser-default custom-select pull-left", :name => "situacao_id"} %>
    </div>
    <div id="btn-filtros">
      <button class="btn btn-sm green-default btn-search btn-circle" type="submit"><i class="fa fa-filter pr-2"></i> Filtrar pedidos</button>
    </div>
  </div>
<% end %>

app/views/pedido_atestados/_index.html.erb
<!-- Modal -->
<div class="modal fade" id="modal_detalhes" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content container-fluid">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">DETALHES</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="detalhes_pedido">
      </div>
      <div class="modal-footer">
      </div>
      </div>
    </div>
  </div>
</div>

<h3 class="py-3">Pedidos</h3>

<%= render partial: 'pedido_atestados/form_busca', :locals => {:path => "pedidos_biblioteca_path"} %>

<div id="lista-pedidos" class="list-group">
  <% @pedido_atestados.each do |pedido_atestado| %>
    <%= link_to '#', :class => 'btn-detalhes mb-1', data: {target: "#modal_detalhes", toggle: "modal", url: pedido_atestados_get_pedido_path(pedido_atestado.id), id: pedido_atestado.id} do %>
      <section class="list-group-item flex-column align-items-start p-2">
        <div class="d-flex w-100 mb-2 justify-content-between badge badge-light p-1">
          <span class="badge blue-default" style="font-size: 14px">Nº Pasta <%= pedido_atestado.pasta %></span>
          <% if ((Date.parse(Date.current.to_s) - Date.parse(pedido_atestado.created_at.to_s)).to_i == 0) then %>
            <small style="font-size: 10px; padding: 5px;">Solicitado Hoje - <b class="text-uppercase">[ <%= pedido_atestado.situacao.descricao %> ]</b></small>
          <% else %>
            <small style="font-size: 10px; padding: 5px;">Solicitado há <%= (Date.parse(Date.current.to_s) - Date.parse(pedido_atestado.created_at.to_s)).to_i %> dia(s) - <b class="text-uppercase">[ <%= pedido_atestado.situacao.descricao %> ]</b></small>
          <% end %>
        </div>
 
        <div class="px-2"><%= pedido_atestado.nome %> (<%= pedido_atestado.curso.descricao %>)</div>
      </section>
    <% end %>
  <% end %>
</div>

app/views/pedido_atestados/get_pedido.js.erb
$( "#detalhes_pedido" ).fadeToggle( "fast", function() {
  $('#detalhes_pedido').html('<%= escape_javascript render(partial: "pedido_atestados/detalhes_pedido") %>').fadeIn(500);
});

app/views/pedido_atestados/get_situacao.js.erb
$( "#andamento_pedido" ).fadeToggle( "fast", function() {
  $('#andamento_pedido').html('<%= escape_javascript render(partial: "pedido_atestados/andamento_pedido") %>').fadeIn(500);
});

app/views/pedido_atestados/new.html.erb
<i class="fa fa-user icone" aria-hidden="true"></i><strong><h7> Módulo Aluno</h7></strong>
<%= link_to aluno_path, :class => 'col-sm-1 pull-right btn green-default btn-sm text-white' do %>
  <i class="fa fa-arrow-left pr-1" aria-hidden="true"></i>
  Voltar
<% end %>
<hr/>

<h4 class="py-3">Formulário de Solicitação</h4>

<%= render 'form', pedido_atestado: @pedido_atestado %>

app/views/pedido_atestados/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>Type:</strong>
  <%= @pedido_atestado.type %>
</p> -->

<p>
  <strong>Nome do aluno:</strong>
  <%= @pedido_atestado.nome %>
</p>

<p>
  <strong>Matrícula:</strong>
  <%= @pedido_atestado.matricula %>
</p>
<p>
  <strong>Pasta:</strong>
  <%= @pedido_atestado.pasta %>
</p>

<p>
  <strong>Turno:</strong>
  <%= @pedido_atestado.turno %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @pedido_atestado.curso.descricao %>
</p>

<p>
  <strong>Período:</strong>
  <%= @pedido_atestado.periodo %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @pedido_atestado.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @pedido_atestado.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pedido_atestado.email %>
</p>

<p>
  <strong>Finalidade do pedido:</strong>
  <%= @pedido_atestado.finalidadePedido %>
</p>

<p>
  <strong>Situação:</strong>
  <%= @pedido_atestado.situacao.descricao %>
</p>

<%= link_to 'Edit', edit_pedido_atestado_path(@pedido_atestado) %> |
<%= link_to 'Back', pedido_atestados_path %>