config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  get 'cursos' => 'cursos#find_by_curso'
  get 'aluno' => 'alunos#index'
  get 'registroacademico' => 'registro_academicos#index'
  get 'biblioteca' => 'bibliotecas#index'
  get 'buscapedido' => 'home#search'
  get 'pedidos_registro' => 'registro_academicos#pedidos'
  get 'pedidos_biblioteca' => 'bibliotecas#pedidos'
  root 'home#index'
  get 'pedido_atestados/get_pedido/:id' => "pedido_atestados#get_pedido", as: "pedido_atestados_get_pedido"
  get 'pedido_atestados/get_situacao' => "pedido_atestados#get_situacao", as: "pedido_atestados_get_situacao"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pedido_atestados
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
  def search
  end
end

app/views/home/home_aluno.html.erb
<h1>Área do Aluno</h1>
<hr/>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to new_pedido_atestado_path, :class => 'btn btn-menu' do %>
    <i class="fa fa-edit fa-5x" aria-hidden="true"></i>
    Solicitar Atestado de Matrícula
  <% end %>
  <%= link_to home_search_path, :class => 'btn btn-menu2' do %>
    <i class="fa fa-search fa-5x" aria-hidden="true"></i>
    Buscar Pedido
  <% end %>
</div>

<br><br><br>
<%= link_to 'Voltar', root_path %>

app/views/home/home_biblioteca.html.erb
<h1>Área da Biblioteca</h1>
<hr/>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to '#', :class => 'btn btn-menu' do %>
    <i class="fa fa-id-badge fa-5x" aria-hidden="true"> </i>
     Aprovação de Nada Consta
  <% end %>
  <%= link_to home_search_path, :class => 'btn btn-menu2' do %>
    <i class="fa fa-search fa-5x" aria-hidden="true"></i>
    Buscar Pedido
  <% end %>
</div>

<br><br><br>

<%= link_to 'Sair', root_path %>

app/views/home/home_registro_academico.html.erb
<h1>Área do Registro Acadêmico</h1>
<hr/>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to '#', :class => 'btn btn-menu' do %>
    <i class="fa fa-list fa-5x" aria-hidden="true"> </i>
     Atendimento de Pedidos
  <% end %>
  <%= link_to home_search_path, :class => 'btn btn-menu2' do %>
    <i class="fa fa-search fa-5x" aria-hidden="true"></i>
    Buscar Pedido
  <% end %>
</div>

<br><br><br>
<%= link_to 'Sair', root_path %>

app/views/home/index.html.erb
<h2>Bem-vindo ao DOCA,<br>Portal de Solicitação de Documentos Acadêmicos</h2>
<div class="pb-4"> Escolha abaixo o módulo que deseja acessar. Dados de login poderão ser necessários.</div>

<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
  <%= link_to aluno_path, :class => 'btn btn-index ml-0 text-left' do %>
    <i class="fa fa-user" aria-hidden="true"></i>
    Aluno
  <% end %>
  <%= link_to registroacademico_path, :class => 'btn btn-index ml-0 text-left' do %>
    <i class="fa fa-id-card-o" aria-hidden="true"></i>
    Registro Acadêmico
  <% end %>
  <%= link_to biblioteca_path, :class => 'btn btn-index ml-0 text-left' do %>
    <i class="fa fa-book" aria-hidden="true"></i>
    Biblioteca
  <% end %>
</div>

app/views/home/search.html.erb
<!-- Modal -->
<div class="modal fade" id="modal_andamento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content container-fluid">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">ANDAMENTO</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="andamento_pedido"></div>
      <div class="modal-footer">
      </div>
      </div>
    </div>
  </div>
</div>

<%= link_to request.referer, :class => 'col-sm-1 pull-right btn green-default btn-sm text-white' do %>
  <i class="fa fa-arrow-left pr-1" aria-hidden="true"></i>
  Voltar
<% end %>
<h4 class="font-weight-bold">Buscar Pedido</h4>
<div> Verifique o andamento dos pedidos referentes ao nº de pasta.</div>
<hr/>

<div id="div-busca">
  <input id="search" class="form-default" type="text" placeholder="Digite um nº de pasta" aria-label="Search" onkeypress="return SomenteNumero(event)" maxlength="6">
  <%= link_to "#", :id => 'btn-search', :class => 'btn blue-default px-3 btn-circle', data: {target: "#modal_andamento", toggle: "modal", url: pedido_atestados_get_situacao_path()} do %>
  <i class="fa fa-search" aria-hidden="true"></i><% end %>
</div>