config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  get 'cursos' => 'cursos#find_by_curso'
  get 'aluno' => 'alunos#index'
  get 'registroacademico' => 'registro_academicos#index'
  get 'biblioteca' => 'bibliotecas#index'
  get 'buscapedido' => 'home#search'
  get 'pedidos_registro' => 'registro_academicos#pedidos'
  get 'pedidos_biblioteca' => 'bibliotecas#pedidos'
  root 'home#index'
  get 'pedido_atestados/get_pedido/:id' => "pedido_atestados#get_pedido", as: "pedido_atestados_get_pedido"
  get 'pedido_atestados/get_situacao' => "pedido_atestados#get_situacao", as: "pedido_atestados_get_situacao"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pedido_atestados
end

app/controllers/registro_academicos_controller.rb
class RegistroAcademicosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :is_registro?  
  before_action -> { filter_pedido_atestado("(2,4,5,6)") }, only: [:pedidos]

  def index
  end

  def pedidos
  end
end

app/helpers/registro_academicos_helper.rb
module RegistroAcademicosHelper
end

app/views/registro_academicos/index.html.erb
<i class="fa fa-id-card-o icone" aria-hidden="true"></i><strong><h7> Módulo Registro Acadêmico</h7></strong>
<%= link_to destroy_usuario_session_path, method: :delete, :class => 'col-sm-1 pull-right btn blue-default btn-sm text-white' do %>
  Sair
  <i class="fa fa-sign-out pl-1" aria-hidden="true"></i>
<% end %>
<hr/>

<div class="btn-group menu-mobile" role="group" aria-label="Basic example">
  <%= link_to asset_path('/modelo-de-recibo.pdf'), target: '_blank', class: 'btn btn-menu' do %>
    <i class="fa fa-print fa-5x pr-2" aria-hidden="true"></i>
     Baixar modelo de recibo
  <% end %>
  <%= link_to pedidos_registro_path, class: 'btn btn-menu' do %>
    <i class="fa fa-list fa-5x pr-2" aria-hidden="true"></i>
     Atendimento de Pedidos
  <% end %>
  <%= link_to buscapedido_path, class: 'btn btn-menu2' do %>
    <i class="fa fa-search fa-5x pr-1" aria-hidden="true"></i>
    Buscar Pedido
  <% end %>
</div>

app/views/registro_academicos/pedidos.html.erb
<div>
  <i class="fa fa-id-card-o icone" aria-hidden="true"></i><strong><h7>  Módulo Registro Acadêmico</h7></strong>
  <%= link_to destroy_usuario_session_path, method: :delete, :class => 'col-sm-1 pull-right btn blue-default btn-sm text-white' do %>
    Sair
    <i class="fa fa-sign-out pl-1" aria-hidden="true"></i>
  <% end %>
  <%= link_to registroacademico_path, :class => 'col-sm-1 pull-right btn green-default btn-sm text-white' do %>
    <i class="fa fa-arrow-left pr-1" aria-hidden="true"></i>
    Voltar
  <% end %>
  <hr/>

  <div class="container-fluid">
    <%= render partial: 'pedido_atestados/index' %>
  </div>
</div>