config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  get 'cursos' => 'cursos#find_by_curso'
  get 'aluno' => 'alunos#index'
  get 'registroacademico' => 'registro_academicos#index'
  get 'biblioteca' => 'bibliotecas#index'
  get 'buscapedido' => 'home#search'
  get 'pedidos_registro' => 'registro_academicos#pedidos'
  get 'pedidos_biblioteca' => 'bibliotecas#pedidos'
  root 'home#index'
  get 'pedido_atestados/get_pedido/:id' => "pedido_atestados#get_pedido", as: "pedido_atestados_get_pedido"
  get 'pedido_atestados/get_situacao' => "pedido_atestados#get_situacao", as: "pedido_atestados_get_situacao"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pedido_atestados
end

app/controllers/bibliotecas_controller.rb
class BibliotecasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :is_bibliotecario?
  before_action -> { filter_pedido_atestado("(1, 3)") }, only: [:pedidos]

  def index
  end

  def pedidos
  end
end

app/helpers/bibliotecas_helper.rb
module BibliotecasHelper
end

app/views/bibliotecas/index.html.erb
<i class="fa fa-book icone" aria-hidden="true"></i><strong><h7> Módulo Biblioteca</h7></strong>
<%= link_to destroy_usuario_session_path, method: :delete, :class => 'col-sm-1 pull-right btn blue-default btn-sm text-white' do %>
  Sair
  <i class="fa fa-sign-out pl-1" aria-hidden="true"></i>
<% end %>
<hr/>

<div class="btn-group menu-mobile" role="group" aria-label="Basic example">
  <%= link_to pedidos_biblioteca_path, :class => 'btn btn-menu' do %>
    <i class="fa fa-id-badge fa-5x pr-2" aria-hidden="true"> </i>
     Aprovação de Nada Consta
  <% end %>
  <%= link_to buscapedido_path, :class => 'btn btn-menu2' do %>
    <i class="fa fa-search fa-5x pr-1" aria-hidden="true"></i>
    Buscar Pedido
  <% end %>
</div>

app/views/bibliotecas/pedidos.html.erb
<i class="fa fa-book icone" aria-hidden="true"></i><strong><h7>  Módulo Biblioteca</h7></strong>
<%= link_to destroy_usuario_session_path, method: :delete, :class => 'col-sm-1 pull-right btn blue-default btn-sm text-white' do %>
  Sair
  <i class="fa fa-sign-out pl-1" aria-hidden="true"></i>
<% end %>
<%= link_to biblioteca_path, :class => 'col-sm-1 pull-right btn green-default btn-sm text-white' do %>
  <i class="fa fa-arrow-left pr-1" aria-hidden="true"></i>
  Voltar
<% end %>
<hr/>

<div class="container-fluid">
  <%= render partial: 'pedido_atestados/index', pedido_atestado: @pedido_atestado %>
</div>